language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

os:
    - linux

script:
    - cd src
    - python3 -m unittest -v test_*.py
    - python3 -m unittest discover -v -s check/ -p 'test_*.py'
    - python3 -m unittest discover -v -s format/ -p 'test_*.py'
