language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

os:
    - linux

script:
    - python3 -m unittest discover -v -s src/ -p 'test_*.py'
    - cd src
    - python3 -m unittest discover -v -s src/check -p 'test_*.py'
    - python3 -m unittest discover -v -s src/format -p 'test_*.py'
